# Mandatory: Schema version of the configuration file
schema_version: 2
# Azure Organisation name
azure_devops_organization: <Azure azure_devops_organisation>
log_level: <level: DEBUG, INFO, WARNING, ERRRR, CRITICAL>
# Feature flags to enable/disable specific features
feature_flags:
  # Optional: Enable Azure Cache (default: false)
  enable_azure_cache: true
  # Optional: Enable Brotli middleware for compression (default: false)
  enable_brotli_middleware: true
# Optional: Relative or absolute path to the database directory or full path and filename
database_path: </path/to/database/directory/or/file.yaml>
